COUNTRIES = ['India',
             'Indonesia',
             'Bangladesh',
             'Philippines',
             'Germany',
             'France',
             'United Kingdom',
             'United States',
             'Mexico',
             'Brazil']